//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Resources;
using System.Reflection;

// -----------------------------------------------------------------------------
//  <autogeneratedinfo>
//      This code was generated by:
//        SR Resource Generator custom tool for VS.NET, by Martin Granell, Readify
// 
//      It contains classes defined from the contents of the resource file:
//        D:\Projects\prjSiGlaz\Working\BEDE\Phrase II\Online\SIA.UI.Controls\Automation\Resources\Strings.resx
// 
//      Generated: Thursday, February 22, 2007 6:16 PM
//  </autogeneratedinfo>
// -----------------------------------------------------------------------------
namespace SIA.UI.Controls.Automation.Resources
{       
	internal class Strings
	{
	        
		internal static System.Globalization.CultureInfo Culture
		{
			get
			{
				return Keys.Culture;
			}
			set
			{
				Keys.Culture = value;
			}
		}
		
		internal static string CalculationsStep
		{
			get
			{
				return Keys.GetString(Keys.CalculationsStep);
			}
		}
		
		internal static string ClearWaferboundStep
		{
			get
			{
				return Keys.GetString(Keys.ClearWaferboundStep);
			}
		}
		
		internal static string DetectObjectStep
		{
			get
			{
				return Keys.GetString(Keys.DetectObjectStep);
			}
		}
		
		internal static string DetectWaferBoundStep
		{
			get
			{
				return Keys.GetString(Keys.DetectWaferBoundStep);
			}
		}
		
		internal static string ExportKLARFStep
		{
			get
			{
				return Keys.GetString(Keys.ExportKLARFStep);
			}
		}
		
		internal static string FilterFFTStep
		{
			get
			{
				return Keys.GetString(Keys.FilterFFTStep);
			}
		}
		
		internal static string FilterRankStep
		{
			get
			{
				return Keys.GetString(Keys.FilterRankStep);
			}
		}
		
		internal static string FilterVarianceStep
		{
			get
			{
				return Keys.GetString(Keys.FilterVarianceStep);
			}
		}
		
		internal static string GbcStep
		{
			get
			{
				return Keys.GetString(Keys.GbcStep);
			}
		}
		
		internal static string InvertStep
		{
			get
			{
				return Keys.GetString(Keys.InvertStep);
			}
		}
		
		internal static string KernelFilterStep
		{
			get
			{
				return Keys.GetString(Keys.KernelFilterStep);
			}
		}
		
		internal static string LoadImageStep
		{
			get
			{
				return Keys.GetString(Keys.LoadImageStep);
			}
		}
		
		internal static string LoadWaferBoundaryStep
		{
			get
			{
				return Keys.GetString(Keys.LoadWaferBoundaryStep);
			}
		}
		
		internal static string SaveImageStep
		{
			get
			{
				return Keys.GetString(Keys.SaveImageStep);
			}
		}
		
		internal static string WaferDistortionCorrectionStep
		{
			get
			{
				return Keys.GetString(Keys.WaferDistortionCorrectionStep);
			}
		}
	        
		public class Keys
		{
	            
			static System.Resources.ResourceManager resourceManager = new System.Resources.ResourceManager(typeof(Strings));

			static System.Globalization.CultureInfo _culture = null;

			internal const string CalculationsStep = "CalculationsStep";

			internal const string ClearWaferboundStep = "ClearWaferboundStep";

			internal const string DetectObjectStep = "DetectObjectStep";

			internal const string DetectWaferBoundStep = "DetectWaferBoundStep";

			internal const string ExportKLARFStep = "ExportKLARFStep";

			internal const string FilterFFTStep = "FilterFFTStep";

			internal const string FilterRankStep = "FilterRankStep";

			internal const string FilterVarianceStep = "FilterVarianceStep";

			internal const string GbcStep = "GbcStep";

			internal const string InvertStep = "InvertStep";

			internal const string KernelFilterStep = "KernelFilterStep";

			internal const string LoadImageStep = "LoadImageStep";

			internal const string LoadWaferBoundaryStep = "LoadWaferBoundaryStep";

			internal const string SaveImageStep = "SaveImageStep";

			internal const string WaferDistortionCorrectionStep = "WaferDistortionCorrectionStep";

			internal const string SaveWaferBoundaryStep = "SaveWaferBoundaryStep";
	            
			internal static System.Globalization.CultureInfo Culture
			{
				get
				{
					return _culture;
				}
				set
				{
					_culture = value;
				}
			}
	            
			internal static string GetString(string key)
			{
				return resourceManager.GetString(key, _culture);
			}

			internal static string GetString(string key, object[] args)
			{
				string msg = resourceManager.GetString(key, _culture);
				msg = string.Format(msg, args);
				return msg;
			}
		}
	}
}
